//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePayment
    {
        public int EmployeePaymentId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public Nullable<decimal> BasicWorkingHours { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> OvertimeHours { get; set; }
        public Nullable<decimal> OvertimePay { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> TaxDeduction { get; set; }
        public Nullable<decimal> NationalInsurance { get; set; }
        public Nullable<decimal> TotalPay { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> EmployeePaymentStatusId { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeePaymentStatus EmployeePaymentStatus { get; set; }
    }
}
